TRUNCATE TABLE phone_extensions RESTART IDENTITY CASCADE;
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('DEPARTAMENTO LA COLINA', 'HERNAN FERNANDEZ', '1010', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('DEPARTAMENTO LA COLINA', 'GABRIEL SANCHEZ', '1011', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('DEPARTAMENTO LA COLINA', 'KARLA RODRIGUEZ', '1012', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('DEPARTAMENTO LA COLINA', 'LUIS CEDEÑO', '1013', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('DEPARTAMENTO LA COLINA', 'BERTTE NUNES', '1014', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('DEPARTAMENTO LA COLINA', 'LISBRAY SUEREZ', '1015', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('DEPARTAMENTO LA COLINA', 'DELIA MONIZ', '1016', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('PLANIFICACION', 'GENERAL', '6000', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('PLANIFICACION', 'DAHOMY VIVAS', '1017', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('PLANIFICACION', 'ENDERLIN VEGAS', '1022', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('PLANIFICACION', 'GEO NORIEGA', '1023', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('PLANIFICACION', 'YENIFER TORRES', '1031', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('PLANIFICACION', 'ZUYERLIN RAMIREZ', '1024', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE LA COLINA', 'ESMERALDA DELGADO', '1019', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE LA COLINA', 'SHERESADE GIL', '1018', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE LA COLINA', 'VIVIANA CARREÑO (CORPORATIVOS)', '1035', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('RRHH', 'CLAUDIA MILLAN', '1021', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('RRHH', 'STEPHANIE GONCALVES', '1036', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('RRHH', 'ANTONELLA GONCALVES', '1029', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('ESPECIALISTA EN REDES', 'NOC', '-', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('ESPECIALISTA EN REDES', 'HAGGYN SUBEROS', '-', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('ESPECIALISTA EN REDES', 'IVAN CAMACHO', '2012', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('ESPECIALISTA EN REDES', 'BRANDON CARRERO', '2011', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('ESPECIALISTA EN REDES', 'DIXON IGLESIA', '2010', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'GENERAL SOPORTE', '6002', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ROBERTO SANTOS', '2013', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA EN SOPORTE1', '2014', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA EN SOPORTE2', '2015', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA EN SOPORTE3', '2016', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA EN SOPORTE4', '2017', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA EN SOPORTE5', '2018', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA EN SOPORTE6', '2019', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA CALL1 SOPORTE', '2022', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA CALL2 SOPORTE', '2021', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA CALL3 SOPORTE', '2029', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA CALL4 SOPORTE', '2030', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SOPORTE', 'ANALISTA CALL5 SOPORTE', '2035', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('CALL CENTER', 'GENERAL', '6001', TRUE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('CALL CENTER', 'CESIRETH', '2023', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('CALL CENTER', 'ARIANDNE', '2025', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('CALL CENTER', 'MAURO', '2024', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('CALL CENTER', 'SEBASTIAN', '2026', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('CALL CENTER', 'POR ASIGNAR', '2027', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('INTEGRACION', 'LUIS AUGUSTO', '1020', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('INTEGRACION', 'WHILLY GALLARDO', '2020', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('INTEGRACION', 'ABRAHAM RAGA', '2031', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE ALI PRIMERA', 'IVOON VIANA', '3012', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE ALI PRIMERA', 'BARBARA MARQUEZ', '3015', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('HEDEZ SISTEM', 'RENE RANGEL HEDEZSYSTEM', '3010', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('HEDEZ SISTEM', 'HEDEZSYSTEM2 HEDEZSYSTEM', '3011', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE INDEPENDENCIA', 'ALEJANDRO SANCHEZ', '4012', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE INDEPENDENCIA', 'RODGER INFANTE', '4010', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE INDEPENDENCIA', 'POR ASIGNAR', '4011', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE EL VALLE', 'JOHANIR CAÑIZALES', '5010', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE EL VALLE', 'HECTOR MENDOZA', '5012', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE EL VALLE', 'STEPHANIE CONTRERAS', '5011', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE PROPATRIA', 'DADIUSKA RINCONES', '6010', FALSE);
INSERT INTO phone_extensions (department, name, extension, is_group) VALUES ('SEDE TEJERIAS', 'YULEISY CAMPOMAS', '7010', FALSE);